### ISSUE TITLE
Auto increment Not working

### ISSUE THREAD

**Issue by WoodyJ007** [drualcman/BlasorIndexedDb#1]
Hi, I can't seem to get auto increment working.  I've tried setting all different kinds of combinations but the error message is either can't match model or failed transaction.  Is there a working sample of this or a bug?

Thanks

**Comment by drualcman** [comment]
Thanks for your comment. Yes, we are working on that issue already, but really I didn't have time to check. It's open source you canhelp, this issue is in the JAVASCRIPT file.

I will feedback you here if it's fixed.

I usually I control from C# get last ID and then ++
