### ISSUE TITLE
Bug: Update model

### ISSUE THREAD

**Issue by williamchenicon** [drualcman/BlasorIndexedDb#3]
Hello,

I found a bug.

https://github.com/drualcman/BlasorIndexedDb/blob/03640ba12f82f17813e9acaa258862ef9dad985c/BlasorIndexedDb/wwwroot/MyDbJS.js#L157

if (obj2[attrname1]) obj3[attrname1] = obj2[attrname1];     //only if the property exists update

Cannot handle if the value of obj2 is 0 , bool false or null.

Maybe this :
if (typeof obj2[attrname1] !== 'undefined'')

**Comment by drualcman** [comment]
Thanks for the report. I am happy if you can fork and send a push request. 

I will work on that. Can you send to me the code example to test the issue?

**Comment by williamchenicon** [comment]
Example.

If current model is :

{
    Name:  "test name",
    Income:  10,
    Address: "xxxxxxx",
    Married: true
}

And I want to update model  to 

{
     Name:  "test name",
    Income:  0,
    Address: null,
    Married: false
}


Then below 3 fields won't be updated as it is false with this code: if (obj2[attrname1])
{
    Income:  0,
    Address: null,
    Married: false
}

**Comment by drualcman** [comment]
Thanks. I will work with this example now.

**Comment by williamchenicon** [comment]
Thanks

**Comment by williamchenicon** [comment]
I added another commit to fix SelectedId problem.

It currently calls wrong method: Select, so it just returns all data in a table and pick the 1st one

**Comment by drualcman** [comment]
Thanks, I am traveling and don't have time yet to check, maybe next week.

Looking into your fixed about the Id, maybe also it's needed in the SelectWhere. So first we need to Select Table then search by column and value.

Thanks so much for your contributions, sure by next week should be tested and merged.

**Comment by drualcman** [comment]
Thanks to fix this bug, your commit it's already merged.
